<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'TIProjects\Module'                        => __DIR__ . '/Module.php',
    'TIProjects\Controller\TIProjectsController' => __DIR__ . '/src/TIProjects/Controller/TIProjectsController.php',
    'TIProjectsTest\Framework\TestCase'        => __DIR__ . '/tests/TIProjects/Framework/TestCase.php',
    'TIProjectsTest\SampleTest'                => __DIR__ . '/tests/TIProjects/SampleTest.php',
);
