<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Challenges\Module'                        => __DIR__ . '/Module.php',
    'Challenges\Controller\ChallengesController' => __DIR__ . '/src/Challenges/Controller/ChallengesController.php',
    'ChallengesTest\Framework\TestCase'        => __DIR__ . '/tests/Challenges/Framework/TestCase.php',
    'ChallengesTest\SampleTest'                => __DIR__ . '/tests/Challenges/SampleTest.php',
);
