<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'UserAdministration\Module'                        => __DIR__ . '/Module.php',
    'UserAdministration\Controller\UserAdministrationController' => __DIR__ . '/src/UserAdministration/Controller/UserAdministrationController.php',
    'UserAdministrationTest\Framework\TestCase'        => __DIR__ . '/tests/UserAdministration/Framework/TestCase.php',
    'UserAdministrationTest\SampleTest'                => __DIR__ . '/tests/UserAdministration/SampleTest.php',
);
