<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Authentication\Module'                        => __DIR__ . '/Module.php',
    'Authentication\Controller\AuthenticationController' => __DIR__ . '/src/Authentication/Controller/AuthenticationController.php',
    'AuthenticationTest\Framework\TestCase'        => __DIR__ . '/tests/Authentication/Framework/TestCase.php',
    'AuthenticationTest\SampleTest'                => __DIR__ . '/tests/Authentication/SampleTest.php',
);
