<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'UserPassport\Module'                        => __DIR__ . '/Module.php',
    'UserPassport\Controller\UserPassportController' => __DIR__ . '/src/UserPassport/Controller/UserPassportController.php',
    'UserPassportTest\Framework\TestCase'        => __DIR__ . '/tests/UserPassport/Framework/TestCase.php',
    'UserPassportTest\SampleTest'                => __DIR__ . '/tests/UserPassport/SampleTest.php',
);
