<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Profile\Module'                        => __DIR__ . '/Module.php',
    'Profile\Controller\ProfileController' => __DIR__ . '/src/Profile/Controller/ProfileController.php',
    'ProfileTest\Framework\TestCase'        => __DIR__ . '/tests/Profile/Framework/TestCase.php',
    'ProfileTest\SampleTest'                => __DIR__ . '/tests/Profile/SampleTest.php',
);
