<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'HostedProjects\Module'                        => __DIR__ . '/Module.php',
    'HostedProjects\Controller\HostedProjectsController' => __DIR__ . '/src/HostedProjects/Controller/HostedProjectsController.php',
    'HostedProjectsTest\Framework\TestCase'        => __DIR__ . '/tests/HostedProjects/Framework/TestCase.php',
    'HostedProjectsTest\SampleTest'                => __DIR__ . '/tests/HostedProjects/SampleTest.php',
);
