<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Match\Module'                        => __DIR__ . '/Module.php',
    'Match\Controller\MatchController' => __DIR__ . '/src/Match/Controller/MatchController.php',
    'MatchTest\Framework\TestCase'        => __DIR__ . '/tests/Match/Framework/TestCase.php',
    'MatchTest\SampleTest'                => __DIR__ . '/tests/Match/SampleTest.php',
);
