<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Provisioning\Module'                        => __DIR__ . '/Module.php',
    'Provisioning\Controller\ProvisioningController' => __DIR__ . '/src/Provisioning/Controller/ProvisioningController.php',
    'ProvisioningTest\Framework\TestCase'        => __DIR__ . '/tests/Provisioning/Framework/TestCase.php',
    'ProvisioningTest\SampleTest'                => __DIR__ . '/tests/Provisioning/SampleTest.php',
    'Tenant' => __DIR__ . '/../../vendor/epalsAPIs/php/tenant.php',
    'Course' => __DIR__ . '/../../vendor/epalsAPIs/php/course.php',
    'Teacher' => __DIR__ . '/../../vendor/epalsAPIs/php/teacher.php',
    'Student' => __DIR__ . '/../../vendor/epalsAPIs/php/student.php',
    'UserPreference' => __DIR__ . '/../../vendor/epalsAPIs/php/UserPreference.php',
    'School' => __DIR__ . '/../../vendor/epalsAPIs/php/school.php',
    'User' => __DIR__ . '/../../vendor/epalsAPIs/php/user.php',
    'UserAttribute' => __DIR__ . '/../../vendor/epalsAPIs/php/UserAttribute.php',
    'Course' => __DIR__ . '/../../vendor/epalsAPIs/php/course.php',
    'Parental' => __DIR__ . '/../../vendor/epalsAPIs/php/parental.php',
    
);
